### PR TITLE
Made black ones appear on grey lines #265

### PR DESCRIPTION
**Pull request by Chaitu-Tatipamula**
z-index attribute of the grey lines fixed this issue.

### CODE REVIEW

**Comment by Chaitu-Tatipamula** [comment]
@therealryan  is this the way to raise a PR

**Review by therealryan — CHANGES_REQUESTED** [review]
Is the change to report/report-ng/projects/report/src/styles.css required for the z-order fix? If not, we should remove that change from the PR.

**Comment by Chaitu-Tatipamula** [comment]
Ok ill change and will let you know when done

**Comment by Chaitu-Tatipamula** [comment]
pr #276

**Comment by therealryan** [comment]
The sonar test is failing, but that's because the fork doesn't have access to the auth token for the upload to sonar. It'd beggar belief that this failure was masking sonar issues in the change.

**Review by therealryan — APPROVED** [review]
Looks good!

**Comment by therealryan** [comment]
Congratulations to @Chaitu-Tatipamula for being the first external contributor to this project!
🥇

**Comment by Chaitu-Tatipamula** [comment]
Thank you..😀

**Comment by Chaitu-Tatipamula** [comment]
@therealryan hey can you tell me what this open source is i kinda like this kind of fixing issues but does it really help me for my future career like direct hiring if i really contribute to great projects

**Comment by therealryan** [comment]
@Chaitu-Tatipamula While I can't really offer useful career advice, it seems to me that having a public history of self-motivated exposure to a bunch of different technologies, problem solving, etc, can only be a good thing.

**Comment by Chaitu-Tatipamula** [comment]
@therealryan thanks for the information ☺️

**Pull request merged**
